name: Send Discord Webhook

# Trigger manually with a button in GitHub Actions UI
on: 
  workflow_dispatch:

jobs:
  discord-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to Discord Webhook
        run: |
          curl -X POST "$WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d '{"content": "This is a message sent from GitHub Actions!"}'
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
